[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyynl"
authors = [
    {name = "Donald Hunter", email = "donald.hunter@gmail.com"},
    {name = "Jakub Kicinski", email = "kuba@kernel.org"},
]
description = "yaml netlink (ynl)"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    "pyyaml==6.*",
    "jsonschema==4.*"
]

[tool.setuptools.packages.find]
include = ["pyynl", "pyynl.lib"]

[project.scripts]
ynl = "pyynl.cli:main"
ynl-ethtool = "pyynl.ethtool:main"
